### ISSUE TITLE
Find EmailTemplate By Name And Namespace

### ISSUE THREAD

**Issue by Saify** [ijazfx/graphenee#5]
Find EmailTemplate by TemplateName and Namespace
If Namespace is not provided find EmailTemplate using System Namespace
If System Namespace does not exist fetch EmailTemplate by matching TemplateName only

**Comment by ijazfx** [comment]
@Saify - is this issue completed?

**Comment by ijazfx** [comment]
@Saify - is this issue completed or not? if yes then please close the issue.

**Comment by Saify** [comment]
@ijazfx Yes issue is fixed will close it.
